// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: sentinel.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SentinelService_Ingest_FullMethodName        = "/sentinel.v1.SentinelService/Ingest"
	SentinelService_HealthCheck_FullMethodName   = "/sentinel.v1.SentinelService/HealthCheck"
	SentinelService_GetTaskStatus_FullMethodName = "/sentinel.v1.SentinelService/GetTaskStatus"
	SentinelService_ListTasks_FullMethodName     = "/sentinel.v1.SentinelService/ListTasks"
	SentinelService_ApproveTask_FullMethodName   = "/sentinel.v1.SentinelService/ApproveTask"
	SentinelService_RejectTask_FullMethodName    = "/sentinel.v1.SentinelService/RejectTask"
)

// SentinelServiceClient is the client API for SentinelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SentinelServiceClient interface {
	Ingest(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	GetTaskStatus(ctx context.Context, in *GetTaskStatusRequest, opts ...grpc.CallOption) (*GetTaskStatusResponse, error)
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	ApproveTask(ctx context.Context, in *ApproveTaskRequest, opts ...grpc.CallOption) (*ApproveTaskResponse, error)
	RejectTask(ctx context.Context, in *RejectTaskRequest, opts ...grpc.CallOption) (*RejectTaskResponse, error)
}

type sentinelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSentinelServiceClient(cc grpc.ClientConnInterface) SentinelServiceClient {
	return &sentinelServiceClient{cc}
}

func (c *sentinelServiceClient) Ingest(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestResponse)
	err := c.cc.Invoke(ctx, SentinelService_Ingest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, SentinelService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelServiceClient) GetTaskStatus(ctx context.Context, in *GetTaskStatusRequest, opts ...grpc.CallOption) (*GetTaskStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskStatusResponse)
	err := c.cc.Invoke(ctx, SentinelService_GetTaskStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelServiceClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, SentinelService_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelServiceClient) ApproveTask(ctx context.Context, in *ApproveTaskRequest, opts ...grpc.CallOption) (*ApproveTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveTaskResponse)
	err := c.cc.Invoke(ctx, SentinelService_ApproveTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelServiceClient) RejectTask(ctx context.Context, in *RejectTaskRequest, opts ...grpc.CallOption) (*RejectTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectTaskResponse)
	err := c.cc.Invoke(ctx, SentinelService_RejectTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SentinelServiceServer is the server API for SentinelService service.
// All implementations must embed UnimplementedSentinelServiceServer
// for forward compatibility.
type SentinelServiceServer interface {
	Ingest(context.Context, *IngestRequest) (*IngestResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	GetTaskStatus(context.Context, *GetTaskStatusRequest) (*GetTaskStatusResponse, error)
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	ApproveTask(context.Context, *ApproveTaskRequest) (*ApproveTaskResponse, error)
	RejectTask(context.Context, *RejectTaskRequest) (*RejectTaskResponse, error)
	mustEmbedUnimplementedSentinelServiceServer()
}

// UnimplementedSentinelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSentinelServiceServer struct{}

func (UnimplementedSentinelServiceServer) Ingest(context.Context, *IngestRequest) (*IngestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ingest not implemented")
}
func (UnimplementedSentinelServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedSentinelServiceServer) GetTaskStatus(context.Context, *GetTaskStatusRequest) (*GetTaskStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskStatus not implemented")
}
func (UnimplementedSentinelServiceServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedSentinelServiceServer) ApproveTask(context.Context, *ApproveTaskRequest) (*ApproveTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveTask not implemented")
}
func (UnimplementedSentinelServiceServer) RejectTask(context.Context, *RejectTaskRequest) (*RejectTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectTask not implemented")
}
func (UnimplementedSentinelServiceServer) mustEmbedUnimplementedSentinelServiceServer() {}
func (UnimplementedSentinelServiceServer) testEmbeddedByValue()                         {}

// UnsafeSentinelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SentinelServiceServer will
// result in compilation errors.
type UnsafeSentinelServiceServer interface {
	mustEmbedUnimplementedSentinelServiceServer()
}

func RegisterSentinelServiceServer(s grpc.ServiceRegistrar, srv SentinelServiceServer) {
	// If the following call panics, it indicates UnimplementedSentinelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SentinelService_ServiceDesc, srv)
}

func _SentinelService_Ingest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelServiceServer).Ingest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SentinelService_Ingest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelServiceServer).Ingest(ctx, req.(*IngestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SentinelService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SentinelService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SentinelService_GetTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelServiceServer).GetTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SentinelService_GetTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelServiceServer).GetTaskStatus(ctx, req.(*GetTaskStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SentinelService_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelServiceServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SentinelService_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelServiceServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SentinelService_ApproveTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelServiceServer).ApproveTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SentinelService_ApproveTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelServiceServer).ApproveTask(ctx, req.(*ApproveTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SentinelService_RejectTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelServiceServer).RejectTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SentinelService_RejectTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelServiceServer).RejectTask(ctx, req.(*RejectTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SentinelService_ServiceDesc is the grpc.ServiceDesc for SentinelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SentinelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sentinel.v1.SentinelService",
	HandlerType: (*SentinelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ingest",
			Handler:    _SentinelService_Ingest_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _SentinelService_HealthCheck_Handler,
		},
		{
			MethodName: "GetTaskStatus",
			Handler:    _SentinelService_GetTaskStatus_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _SentinelService_ListTasks_Handler,
		},
		{
			MethodName: "ApproveTask",
			Handler:    _SentinelService_ApproveTask_Handler,
		},
		{
			MethodName: "RejectTask",
			Handler:    _SentinelService_RejectTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sentinel.proto",
}
