// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: sentinel.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogTag) Reset() {
	*x = LogTag{}
	mi := &file_sentinel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogTag) ProtoMessage() {}

func (x *LogTag) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogTag.ProtoReflect.Descriptor instead.
func (*LogTag) Descriptor() ([]byte, []int) {
	return file_sentinel_proto_rawDescGZIP(), []int{0}
}

func (x *LogTag) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LogTag) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type AIContext struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TaskId         string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	LoopDepth      int32                  `protobuf:"varint,3,opt,name=loop_depth,json=loopDepth,proto3" json:"loop_depth,omitempty"`
	Model          string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Confidence     float64                `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ReasoningTrace string                 `protobuf:"bytes,6,opt,name=reasoning_trace,json=reasoningTrace,proto3" json:"reasoning_trace,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AIContext) Reset() {
	*x = AIContext{}
	mi := &file_sentinel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIContext) ProtoMessage() {}

func (x *AIContext) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIContext.ProtoReflect.Descriptor instead.
func (*AIContext) Descriptor() ([]byte, []int) {
	return file_sentinel_proto_rawDescGZIP(), []int{1}
}

func (x *AIContext) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AIContext) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AIContext) GetLoopDepth() int32 {
	if x != nil {
		return x.LoopDepth
	}
	return 0
}

func (x *AIContext) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AIContext) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AIContext) GetReasoningTrace() string {
	if x != nil {
		return x.ReasoningTrace
	}
	return ""
}

type AgentBackLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Result        string                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentBackLogEntry) Reset() {
	*x = AgentBackLogEntry{}
	mi := &file_sentinel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentBackLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentBackLogEntry) ProtoMessage() {}

func (x *AgentBackLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentBackLogEntry.ProtoReflect.Descriptor instead.
func (*AgentBackLogEntry) Descriptor() ([]byte, []int) {
	return file_sentinel_proto_rawDescGZIP(), []int{2}
}

func (x *AgentBackLogEntry) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentBackLogEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AgentBackLogEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *AgentBackLogEntry) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *AgentBackLogEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type IngestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Boundary      string                 `protobuf:"bytes,4,opt,name=boundary,proto3" json:"boundary,omitempty"`
	ServiceId     string                 `protobuf:"bytes,5,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	IsCritical    bool                   `protobuf:"varint,6,opt,name=is_critical,json=isCritical,proto3" json:"is_critical,omitempty"`
	Message       string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	Origin        string                 `protobuf:"bytes,8,opt,name=origin,proto3" json:"origin,omitempty"`
	Tags          []*LogTag              `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	ActorId       string                 `protobuf:"bytes,10,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	SpanId        string                 `protobuf:"bytes,11,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	ParentSpanId  string                 `protobuf:"bytes,12,opt,name=parent_span_id,json=parentSpanId,proto3" json:"parent_span_id,omitempty"`
	ResourceIds   []string               `protobuf:"bytes,13,rep,name=resource_ids,json=resourceIds,proto3" json:"resource_ids,omitempty"`
	AiContext     *AIContext             `protobuf:"bytes,14,opt,name=ai_context,json=aiContext,proto3" json:"ai_context,omitempty"`
	AgentBackLog  []*AgentBackLogEntry   `protobuf:"bytes,15,rep,name=agent_back_log,json=agentBackLog,proto3" json:"agent_back_log,omitempty"`
	Input         string                 `protobuf:"bytes,16,opt,name=input,proto3" json:"input,omitempty"`
	TriggerAgent  bool                   `protobuf:"varint,17,opt,name=trigger_agent,json=triggerAgent,proto3" json:"trigger_agent,omitempty"`
	Details       map[string]string      `protobuf:"bytes,18,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_sentinel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_sentinel_proto_rawDescGZIP(), []int{3}
}

func (x *IngestRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *IngestRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *IngestRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *IngestRequest) GetBoundary() string {
	if x != nil {
		return x.Boundary
	}
	return ""
}

func (x *IngestRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *IngestRequest) GetIsCritical() bool {
	if x != nil {
		return x.IsCritical
	}
	return false
}

func (x *IngestRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *IngestRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *IngestRequest) GetTags() []*LogTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *IngestRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *IngestRequest) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *IngestRequest) GetParentSpanId() string {
	if x != nil {
		return x.ParentSpanId
	}
	return ""
}

func (x *IngestRequest) GetResourceIds() []string {
	if x != nil {
		return x.ResourceIds
	}
	return nil
}

func (x *IngestRequest) GetAiContext() *AIContext {
	if x != nil {
		return x.AiContext
	}
	return nil
}

func (x *IngestRequest) GetAgentBackLog() []*AgentBackLogEntry {
	if x != nil {
		return x.AgentBackLog
	}
	return nil
}

func (x *IngestRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *IngestRequest) GetTriggerAgent() bool {
	if x != nil {
		return x.TriggerAgent
	}
	return false
}

func (x *IngestRequest) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type IngestResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TraceId        string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	HashChainValid bool                   `protobuf:"varint,2,opt,name=hash_chain_valid,json=hashChainValid,proto3" json:"hash_chain_valid,omitempty"`
	Masked         bool                   `protobuf:"varint,3,opt,name=masked,proto3" json:"masked,omitempty"`
	TasksGenerated []*TaskResult          `protobuf:"bytes,4,rep,name=tasks_generated,json=tasksGenerated,proto3" json:"tasks_generated,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_sentinel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_sentinel_proto_rawDescGZIP(), []int{4}
}

func (x *IngestResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *IngestResponse) GetHashChainValid() bool {
	if x != nil {
		return x.HashChainValid
	}
	return false
}

func (x *IngestResponse) GetMasked() bool {
	if x != nil {
		return x.Masked
	}
	return false
}

func (x *IngestResponse) GetTasksGenerated() []*TaskResult {
	if x != nil {
		return x.TasksGenerated
	}
	return nil
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	RuleId        string                 `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	DispatchedAt  string                 `protobuf:"bytes,4,opt,name=dispatched_at,json=dispatchedAt,proto3" json:"dispatched_at,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_sentinel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_sentinel_proto_rawDescGZIP(), []int{5}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *TaskResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskResult) GetDispatchedAt() string {
	if x != nil {
		return x.DispatchedAt
	}
	return ""
}

func (x *TaskResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_sentinel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_sentinel_proto_rawDescGZIP(), []int{6}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_sentinel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_sentinel_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetTaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskStatusRequest) Reset() {
	*x = GetTaskStatusRequest{}
	mi := &file_sentinel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatusRequest) ProtoMessage() {}

func (x *GetTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_sentinel_proto_rawDescGZIP(), []int{8}
}

func (x *GetTaskStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	RuleId         string                 `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	EventName      string                 `protobuf:"bytes,3,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ActionType     string                 `protobuf:"bytes,5,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	Severity       string                 `protobuf:"bytes,6,opt,name=severity,proto3" json:"severity,omitempty"`
	ExecutionLevel string                 `protobuf:"bytes,7,opt,name=execution_level,json=executionLevel,proto3" json:"execution_level,omitempty"`
	Description    string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	SourceTraceId  string                 `protobuf:"bytes,9,opt,name=source_trace_id,json=sourceTraceId,proto3" json:"source_trace_id,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,12,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTaskStatusResponse) Reset() {
	*x = GetTaskStatusResponse{}
	mi := &file_sentinel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatusResponse) ProtoMessage() {}

func (x *GetTaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatusResponse.ProtoReflect.Descriptor instead.
func (*GetTaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_sentinel_proto_rawDescGZIP(), []int{9}
}

func (x *GetTaskStatusResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetTaskStatusResponse) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *GetTaskStatusResponse) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *GetTaskStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetTaskStatusResponse) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *GetTaskStatusResponse) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *GetTaskStatusResponse) GetExecutionLevel() string {
	if x != nil {
		return x.ExecutionLevel
	}
	return ""
}

func (x *GetTaskStatusResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetTaskStatusResponse) GetSourceTraceId() string {
	if x != nil {
		return x.SourceTraceId
	}
	return ""
}

func (x *GetTaskStatusResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetTaskStatusResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GetTaskStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventName     string                 `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	FromTime      string                 `protobuf:"bytes,3,opt,name=from_time,json=fromTime,proto3" json:"from_time,omitempty"`
	ToTime        string                 `protobuf:"bytes,4,opt,name=to_time,json=toTime,proto3" json:"to_time,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_sentinel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_sentinel_proto_rawDescGZIP(), []int{10}
}

func (x *ListTasksRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *ListTasksRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListTasksRequest) GetFromTime() string {
	if x != nil {
		return x.FromTime
	}
	return ""
}

func (x *ListTasksRequest) GetToTime() string {
	if x != nil {
		return x.ToTime
	}
	return ""
}

func (x *ListTasksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTasksRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListTasksResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Tasks         []*GetTaskStatusResponse `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	TotalCount    int32                    `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_sentinel_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_sentinel_proto_rawDescGZIP(), []int{11}
}

func (x *ListTasksResponse) GetTasks() []*GetTaskStatusResponse {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ApproveTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ApproverId    string                 `protobuf:"bytes,2,opt,name=approver_id,json=approverId,proto3" json:"approver_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveTaskRequest) Reset() {
	*x = ApproveTaskRequest{}
	mi := &file_sentinel_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveTaskRequest) ProtoMessage() {}

func (x *ApproveTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveTaskRequest.ProtoReflect.Descriptor instead.
func (*ApproveTaskRequest) Descriptor() ([]byte, []int) {
	return file_sentinel_proto_rawDescGZIP(), []int{12}
}

func (x *ApproveTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ApproveTaskRequest) GetApproverId() string {
	if x != nil {
		return x.ApproverId
	}
	return ""
}

func (x *ApproveTaskRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ApproveTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	DispatchedAt  string                 `protobuf:"bytes,3,opt,name=dispatched_at,json=dispatchedAt,proto3" json:"dispatched_at,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveTaskResponse) Reset() {
	*x = ApproveTaskResponse{}
	mi := &file_sentinel_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveTaskResponse) ProtoMessage() {}

func (x *ApproveTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveTaskResponse.ProtoReflect.Descriptor instead.
func (*ApproveTaskResponse) Descriptor() ([]byte, []int) {
	return file_sentinel_proto_rawDescGZIP(), []int{13}
}

func (x *ApproveTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ApproveTaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApproveTaskResponse) GetDispatchedAt() string {
	if x != nil {
		return x.DispatchedAt
	}
	return ""
}

func (x *ApproveTaskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RejectTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	RejectorId    string                 `protobuf:"bytes,2,opt,name=rejector_id,json=rejectorId,proto3" json:"rejector_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectTaskRequest) Reset() {
	*x = RejectTaskRequest{}
	mi := &file_sentinel_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectTaskRequest) ProtoMessage() {}

func (x *RejectTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectTaskRequest.ProtoReflect.Descriptor instead.
func (*RejectTaskRequest) Descriptor() ([]byte, []int) {
	return file_sentinel_proto_rawDescGZIP(), []int{14}
}

func (x *RejectTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *RejectTaskRequest) GetRejectorId() string {
	if x != nil {
		return x.RejectorId
	}
	return ""
}

func (x *RejectTaskRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RejectTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectTaskResponse) Reset() {
	*x = RejectTaskResponse{}
	mi := &file_sentinel_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectTaskResponse) ProtoMessage() {}

func (x *RejectTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectTaskResponse.ProtoReflect.Descriptor instead.
func (*RejectTaskResponse) Descriptor() ([]byte, []int) {
	return file_sentinel_proto_rawDescGZIP(), []int{15}
}

func (x *RejectTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *RejectTaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_sentinel_proto protoreflect.FileDescriptor

const file_sentinel_proto_rawDesc = "" +
	"\n" +
	"\x0esentinel.proto\x12\vsentinel.v1\"6\n" +
	"\x06LogTag\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\"\xbd\x01\n" +
	"\tAIContext\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"loop_depth\x18\x03 \x01(\x05R\tloopDepth\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01R\n" +
	"confidence\x12'\n" +
	"\x0freasoning_trace\x18\x06 \x01(\tR\x0ereasoningTrace\"\x94\x01\n" +
	"\x11AgentBackLogEntry\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x12\x16\n" +
	"\x06result\x18\x04 \x01(\tR\x06result\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"\xbf\x05\n" +
	"\rIngestRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x1a\n" +
	"\bboundary\x18\x04 \x01(\tR\bboundary\x12\x1d\n" +
	"\n" +
	"service_id\x18\x05 \x01(\tR\tserviceId\x12\x1f\n" +
	"\vis_critical\x18\x06 \x01(\bR\n" +
	"isCritical\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12\x16\n" +
	"\x06origin\x18\b \x01(\tR\x06origin\x12'\n" +
	"\x04tags\x18\t \x03(\v2\x13.sentinel.v1.LogTagR\x04tags\x12\x19\n" +
	"\bactor_id\x18\n" +
	" \x01(\tR\aactorId\x12\x17\n" +
	"\aspan_id\x18\v \x01(\tR\x06spanId\x12$\n" +
	"\x0eparent_span_id\x18\f \x01(\tR\fparentSpanId\x12!\n" +
	"\fresource_ids\x18\r \x03(\tR\vresourceIds\x125\n" +
	"\n" +
	"ai_context\x18\x0e \x01(\v2\x16.sentinel.v1.AIContextR\taiContext\x12D\n" +
	"\x0eagent_back_log\x18\x0f \x03(\v2\x1e.sentinel.v1.AgentBackLogEntryR\fagentBackLog\x12\x14\n" +
	"\x05input\x18\x10 \x01(\tR\x05input\x12#\n" +
	"\rtrigger_agent\x18\x11 \x01(\bR\ftriggerAgent\x12A\n" +
	"\adetails\x18\x12 \x03(\v2'.sentinel.v1.IngestRequest.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaf\x01\n" +
	"\x0eIngestResponse\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12(\n" +
	"\x10hash_chain_valid\x18\x02 \x01(\bR\x0ehashChainValid\x12\x16\n" +
	"\x06masked\x18\x03 \x01(\bR\x06masked\x12@\n" +
	"\x0ftasks_generated\x18\x04 \x03(\v2\x17.sentinel.v1.TaskResultR\x0etasksGenerated\"\x91\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\tR\x06ruleId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rdispatched_at\x18\x04 \x01(\tR\fdispatchedAt\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\x14\n" +
	"\x12HealthCheckRequest\"G\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"/\n" +
	"\x14GetTaskStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\x93\x03\n" +
	"\x15GetTaskStatusResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\tR\x06ruleId\x12\x1d\n" +
	"\n" +
	"event_name\x18\x03 \x01(\tR\teventName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1f\n" +
	"\vaction_type\x18\x05 \x01(\tR\n" +
	"actionType\x12\x1a\n" +
	"\bseverity\x18\x06 \x01(\tR\bseverity\x12'\n" +
	"\x0fexecution_level\x18\a \x01(\tR\x0eexecutionLevel\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12&\n" +
	"\x0fsource_trace_id\x18\t \x01(\tR\rsourceTraceId\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\x12#\n" +
	"\rerror_message\x18\f \x01(\tR\ferrorMessage\"\xad\x01\n" +
	"\x10ListTasksRequest\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\tfrom_time\x18\x03 \x01(\tR\bfromTime\x12\x17\n" +
	"\ato_time\x18\x04 \x01(\tR\x06toTime\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\"n\n" +
	"\x11ListTasksResponse\x128\n" +
	"\x05tasks\x18\x01 \x03(\v2\".sentinel.v1.GetTaskStatusResponseR\x05tasks\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"f\n" +
	"\x12ApproveTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vapprover_id\x18\x02 \x01(\tR\n" +
	"approverId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x81\x01\n" +
	"\x13ApproveTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rdispatched_at\x18\x03 \x01(\tR\fdispatchedAt\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"e\n" +
	"\x11RejectTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vrejector_id\x18\x02 \x01(\tR\n" +
	"rejectorId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"E\n" +
	"\x12RejectTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xeb\x03\n" +
	"\x0fSentinelService\x12A\n" +
	"\x06Ingest\x12\x1a.sentinel.v1.IngestRequest\x1a\x1b.sentinel.v1.IngestResponse\x12P\n" +
	"\vHealthCheck\x12\x1f.sentinel.v1.HealthCheckRequest\x1a .sentinel.v1.HealthCheckResponse\x12V\n" +
	"\rGetTaskStatus\x12!.sentinel.v1.GetTaskStatusRequest\x1a\".sentinel.v1.GetTaskStatusResponse\x12J\n" +
	"\tListTasks\x12\x1d.sentinel.v1.ListTasksRequest\x1a\x1e.sentinel.v1.ListTasksResponse\x12P\n" +
	"\vApproveTask\x12\x1f.sentinel.v1.ApproveTaskRequest\x1a .sentinel.v1.ApproveTaskResponse\x12M\n" +
	"\n" +
	"RejectTask\x12\x1e.sentinel.v1.RejectTaskRequest\x1a\x1f.sentinel.v1.RejectTaskResponseB;Z9github.com/schro-cat-dev/sentinel-server/internal/grpc/pbb\x06proto3"

var (
	file_sentinel_proto_rawDescOnce sync.Once
	file_sentinel_proto_rawDescData []byte
)

func file_sentinel_proto_rawDescGZIP() []byte {
	file_sentinel_proto_rawDescOnce.Do(func() {
		file_sentinel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sentinel_proto_rawDesc), len(file_sentinel_proto_rawDesc)))
	})
	return file_sentinel_proto_rawDescData
}

var file_sentinel_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_sentinel_proto_goTypes = []any{
	(*LogTag)(nil),                // 0: sentinel.v1.LogTag
	(*AIContext)(nil),             // 1: sentinel.v1.AIContext
	(*AgentBackLogEntry)(nil),     // 2: sentinel.v1.AgentBackLogEntry
	(*IngestRequest)(nil),         // 3: sentinel.v1.IngestRequest
	(*IngestResponse)(nil),        // 4: sentinel.v1.IngestResponse
	(*TaskResult)(nil),            // 5: sentinel.v1.TaskResult
	(*HealthCheckRequest)(nil),    // 6: sentinel.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 7: sentinel.v1.HealthCheckResponse
	(*GetTaskStatusRequest)(nil),  // 8: sentinel.v1.GetTaskStatusRequest
	(*GetTaskStatusResponse)(nil), // 9: sentinel.v1.GetTaskStatusResponse
	(*ListTasksRequest)(nil),      // 10: sentinel.v1.ListTasksRequest
	(*ListTasksResponse)(nil),     // 11: sentinel.v1.ListTasksResponse
	(*ApproveTaskRequest)(nil),    // 12: sentinel.v1.ApproveTaskRequest
	(*ApproveTaskResponse)(nil),   // 13: sentinel.v1.ApproveTaskResponse
	(*RejectTaskRequest)(nil),     // 14: sentinel.v1.RejectTaskRequest
	(*RejectTaskResponse)(nil),    // 15: sentinel.v1.RejectTaskResponse
	nil,                           // 16: sentinel.v1.IngestRequest.DetailsEntry
}
var file_sentinel_proto_depIdxs = []int32{
	0,  // 0: sentinel.v1.IngestRequest.tags:type_name -> sentinel.v1.LogTag
	1,  // 1: sentinel.v1.IngestRequest.ai_context:type_name -> sentinel.v1.AIContext
	2,  // 2: sentinel.v1.IngestRequest.agent_back_log:type_name -> sentinel.v1.AgentBackLogEntry
	16, // 3: sentinel.v1.IngestRequest.details:type_name -> sentinel.v1.IngestRequest.DetailsEntry
	5,  // 4: sentinel.v1.IngestResponse.tasks_generated:type_name -> sentinel.v1.TaskResult
	9,  // 5: sentinel.v1.ListTasksResponse.tasks:type_name -> sentinel.v1.GetTaskStatusResponse
	3,  // 6: sentinel.v1.SentinelService.Ingest:input_type -> sentinel.v1.IngestRequest
	6,  // 7: sentinel.v1.SentinelService.HealthCheck:input_type -> sentinel.v1.HealthCheckRequest
	8,  // 8: sentinel.v1.SentinelService.GetTaskStatus:input_type -> sentinel.v1.GetTaskStatusRequest
	10, // 9: sentinel.v1.SentinelService.ListTasks:input_type -> sentinel.v1.ListTasksRequest
	12, // 10: sentinel.v1.SentinelService.ApproveTask:input_type -> sentinel.v1.ApproveTaskRequest
	14, // 11: sentinel.v1.SentinelService.RejectTask:input_type -> sentinel.v1.RejectTaskRequest
	4,  // 12: sentinel.v1.SentinelService.Ingest:output_type -> sentinel.v1.IngestResponse
	7,  // 13: sentinel.v1.SentinelService.HealthCheck:output_type -> sentinel.v1.HealthCheckResponse
	9,  // 14: sentinel.v1.SentinelService.GetTaskStatus:output_type -> sentinel.v1.GetTaskStatusResponse
	11, // 15: sentinel.v1.SentinelService.ListTasks:output_type -> sentinel.v1.ListTasksResponse
	13, // 16: sentinel.v1.SentinelService.ApproveTask:output_type -> sentinel.v1.ApproveTaskResponse
	15, // 17: sentinel.v1.SentinelService.RejectTask:output_type -> sentinel.v1.RejectTaskResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_sentinel_proto_init() }
func file_sentinel_proto_init() {
	if File_sentinel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sentinel_proto_rawDesc), len(file_sentinel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sentinel_proto_goTypes,
		DependencyIndexes: file_sentinel_proto_depIdxs,
		MessageInfos:      file_sentinel_proto_msgTypes,
	}.Build()
	File_sentinel_proto = out.File
	file_sentinel_proto_goTypes = nil
	file_sentinel_proto_depIdxs = nil
}
